# Generated by Django 3.2.5 on 2021-09-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
